//
// Created by frank_lu on 2020/3/31.
//

#ifndef DORA_MESSAGETYPE_H
#define DORA_MESSAGETYPE_H


enum MessageType {
    SOURCE_LINE, SYNTAX_ERROR,
    PARSER_SUMMARY, INTERPRETER_SUMMARY, COMPILER_SUMMARY,
    MISCELLANEOUS, TOKEN,
    ASSIGN, FETCH, BREAKPOINT, RUNTIME_ERROR,
    CALL, RETURN

};


#endif //DORA_MESSAGETYPE_H
